### ISSUE TITLE
Some Bugs if i Used it in NavigationController

### ISSUE THREAD

**Issue by SadhuRus** [betzerra/EBCardCollectionViewLayout#6]
Hello betzerra! A have some bug in Layout.
I make video:
http://youtu.be/BH-BB_tP7NQ

Please, help me fix it.

**Comment by betzerra** [comment]
I would add 

```
- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    _collectionView.contentOffset = CGPointMake(0, 0);
}
```

on the UIViewController that it's implementing the UICollectionView. Check **feature/vertical** pull request #8
