### ISSUE TITLE
Add property to remove spase between cards

### ISSUE THREAD

**Issue by andwhy** [betzerra/EBCardCollectionViewLayout#9]
Hello friend. Thanks for great control. Can you add property to remove spase between cards?

![ios simulator screen shot 16 2015 20 11 19](https://cloud.githubusercontent.com/assets/2667821/6671819/fcb7c11e-cc18-11e4-8e3a-75b270930508.png)
![ios simulator screen shot 16 2015 20 11 31](https://cloud.githubusercontent.com/assets/2667821/6671820/fcb9cbf8-cc18-11e4-8562-f12b40965f46.png)

It works like i need by pageWidth modification 

    - (CGFloat)pageWidth {
        CGFloat retVal = [self cardWidth];
        return retVal;
    }

**Comment by betzerra** [comment]
To remove space from cards you have to set the `offset` property. 
Take a look at our example in `DemoViewController` :

```
UIOffset anOffset = UIOffsetMake(20, 0);
[(EBCardCollectionViewLayout *)_collectionView.collectionViewLayout setOffset:anOffset];
```

Change it for `UIOffsetMake(0,0)` and you're done :-)

**Comment by andwhy** [comment]
If i set UIOffsetMake(0,0) card will be full screen. I need to see sides of previous and next card but without spaces between.

**Comment by betzerra** [comment]
Oh, I see. 

Hmmm... I don't want to add too many properties in the class because I want it to keep it as simple as possible.

The good news is that you figure out how to get your component to get working, so I would suggest to fork the project until I think about what to do here.
